package name.denyago.streaming.source.db.populate

import io.kotlintest.shouldBe
import io.kotlintest.specs.DescribeSpec
import name.denyago.streaming.source.db.GeneratedReader
import java.io.ByteArrayOutputStream

class ScriptGeneratorTest : DescribeSpec() {

    private val expectedContents = """--- Auto-generated by db_populator.kt
insert into users (id, name)
  values (1, 'Jane'), (2, 'Fred'), (3, 'Jane'),
         (4, 'Fred'), (5, 'Jane'), (6, 'Fred'),
         (7, 'Jane'), (8, 'Fred'), (9, 'Jane'),
         (10, 'Fred');


--- Auto-generated by db_populator.kt
insert into users (id, name)
  values (11, 'Jane'), (12, 'Fred'), (13, 'Jane'),
         (14, 'Fred'), (15, 'Jane'), (16, 'Fred'),
         (17, 'Jane'), (18, 'Fred'), (19, 'Jane'),
         (20, 'Fred');
"""

    init {
        describe("generate") {
            it("writes an SQL script with Users to a file") {
                val out = ByteArrayOutputStream(200000)
                val gen = GeneratedReader()
                    .selectUsers(1..20)
                    .asSequence()
                ScriptGenerator(gen, out).generate(20, 3, 10)

                out.toString() shouldBe expectedContents
            }
        }
    }
}
